---
title: "connect-to-postgresql"
output: html_notebook
---

```{r}
library(tidyverse)
library(DBI)
library(RPostgres)
```

```{r}
con <- DBI::dbConnect(
  RPostgres::Postgres(),
  dbname = Sys.getenv("dbname"),
  host = Sys.getenv("host"),
  port = Sys.getenv("port"),
  user = Sys.getenv("user"),
  password = Sys.getenv("password")
)
```

```{r}
# dbDisconnect(con)
```


```{r}
order_atts_cumsums_enhanced_pg <- tbl(con, "order_atts_cumsums_enhanced")
order_atts_cumsums_enhanced_pg
```

```{r}
# curplotno = 302
curplotno = 1869
# curplotno = 52

pbegin <- order_atts_cumsums_enhanced_pg %>%
  filter(obplotno == curplotno) %>%
  pull(datetimemlls) %>% 
  min(.)

pend <- order_atts_cumsums_enhanced_pg %>%
  filter(obplotno == curplotno) %>%
  pull(datetimemlls) %>% 
  max(.)

pcolor <- function(att, plotno) {
  color = ""
  if (plotno == curplotno) {
    if (att == 'BOVOL') color = "green"
    else if (att == 'SOVOL') color = "red"
    else if (att == 'BTVOL' | att == 'STVOL') color = "#8031A7" #"blue"
    else color = "white"
  } else {
    if (att == 'BOVOL') color = "aquamarine"
    else if (att == 'SOVOL') color = "coral"
    else if (att == 'BTVOL' | att == 'STVOL') color = "#004481" #"cadetblue1"
    else color = "white"
  }
  # print(paste(att, plotno, color))
  return(color)
}

pshape <- function(att, plotno) {
  color = ""
  if (plotno == curplotno) {
    shape = 16
  } else {
    shape = 4
  }
  # print(paste(att, plotno, color))
  return(shape)
}

psize <- function(att, plotno) {
  color = ""
  if (plotno == curplotno) {
    size = 1.0
  } else {
    size = 0.5
  }
  # print(paste(att, plotno, color))
  return(size)
}

plot_df_without_rep_by_vol <- order_atts_cumsums_enhanced_pg %>% 
  filter((datetimemlls >= pbegin & datetimemlls <= pend) & (att == "BOVOL" | att == "SOVOL" | att == "BTVOL" | att == "STVOL") & price > 2145.0 & price < 2205.0) %>%
  mutate(pcolor = map2(att, obplotno, ~pcolor(.x, .y)) %>% unlist(),
         pshape = map2(att, obplotno, ~pshape(.x, .y)) %>% unlist(),
         psize = map2(att, obplotno, ~psize(.x, .y)) %>% unlist())
plot_df_without_rep_by_vol %>% filter(obplotno == curplotno)

order_atts_cumsums_enhanced_pg %>% 
  filter((datetimemlls >= pbegin & datetimemlls <= pend) & (att == "BOVOL" | att == "SOVOL" | att == "BTVOL" | att == "STVOL") & price > 2145.0 & price < 2205.0) %>%
  mutate(pcolor = pmap(list(att, obplotno), function(att, obplotno) {
    pcolor(att, obplotno) %>% unlist()
    print(att)
    }))
```

```{r}
dt_s <- plot_df %>% filter(OBPLOTNO != curplotno & ATT == "SOVOL")
dt_b <- plot_df %>% filter(OBPLOTNO != curplotno & ATT == "BOVOL")
dt_t <- plot_df %>% filter(OBPLOTNO != curplotno & (ATT == "BTVOL" | ATT == "STVOL"))
dt_cp_sb <- plot_df %>% filter(OBPLOTNO == curplotno & ATT != "BTVOL" & ATT != "STVOL")
dt_cp_t <- plot_df %>% filter(OBPLOTNO == curplotno & (ATT == "BTVOL" | ATT == "STVOL"))

ggplot(bind_rows(tibble(dt_s, gr = "s"), tibble(dt_b, gr = "b")), aes(x = NO, y = PRICE)) +
  stat_density2d(geom = "density2d", aes(color = gr)) + 
  scale_color_manual(values=c("s"="#FF0000", "b"="#00FF00")) +
  geom_point(data = dt_t, mapping = aes(x = NO, y = PRICE), 
             color = dt_t$pcolor, shape = dt_t$pshape, size = dt_t$psize) +
  geom_point(data = dt_cp_sb, mapping = aes(x = NO, y = PRICE), 
             color = dt_cp_sb$pcolor, shape = dt_cp_sb$pshape, size = dt_cp_sb$psize) +
  geom_point(data = dt_cp_t, mapping = aes(x = NO, y = PRICE), 
             color = dt_cp_t$pcolor, shape = dt_cp_t$pshape, size = dt_cp_t$psize) +
  theme_bw()
```

