---
title: "OBPlots"
output: html_notebook
---

```{r}
library(tidyverse)
library(gganimate)
library(ggtern)
```


```{r}
obp_dynatts_df <- read_csv("resources/3_obp_dynatts_df.csv")
obp_dynatts_df
```

```{r}
OBPlots_df <- read_csv("resources/2_OBPlots_df.csv")
OBPlots_df
```

```{r}
obp_dynatts_no_df <- left_join(obp_dynatts_df, 
                            OBPlots_df %>% select(NO, TIME), 
                            by = "NO") %>% 
  mutate(TIMEm = as.character(as.integer(TIME / 100000)),
         TIME = as.character(TIME / 1000)) %>% 
  select(NO, SECCODE, DATETIMEMLLS, DATE, TIME, TIMEm, OBPLOTNO, 
         ATT, VAL, SHAREBAL, BPROFIT, SPROFIT, OBPMINTPRICE, OBPMAXTPRICE,
         CBOVOLtdcs, CSOVOLtdcs, BOVOLtdcs, SOVOLtdcs, BTVOLtdcs, STVOLtdcs,
         CBOVOLobpcs, CSOVOLobpcs, BOVOLobpcs, SOVOLobpcs, BTVOLobpcs, STVOLobpcs)
obp_dynatts_no_df
```

```{r}
obp_dynatts_no_price_df <- left_join(obp_dynatts_no_df, 
                                     OBPlots_df %>% select(NO, PRICE, TRADEPRICE, VOLUME), 
                                     by="NO")
obp_dynatts_no_price_df
```

```{r}
temp_df <- obp_dynatts_no_df %>% 
  spread(key = ATT, value = VAL) %>% 
  select(TIME, TIMEm, NO, OBPLOTNO, SOVOL, SOVOLtdcs, SOVOLobpcs)
  # filter(OBPLOTNO == 129)
temp_df
```

```{r}
ggplot(data = temp_df) + 
  # geom_point(mapping = aes(x = NO, y = SOVOL), color = "red") +
  # geom_point(mapping = aes(x = NO, y = SOVOLtdcs), color = "green") +
  geom_point(mapping = aes(x = NO, y = SOVOLobpcs), color = "blue")
```

```{r}
# sm - val median by second

temp_sm_df <- temp_df %>% 
  group_by(TIMEm) %>% 
  summarise(SOVOLobpcs = median(SOVOLobpcs))
temp_sm_df
```


```{r}
ggplot(data = temp_sm_df) + 
  geom_point(mapping = aes(x = TIMEm, y = SOVOLobpcs), color = "blue")
```

```{r}
obp_atts_by_obp_df <- read_csv("resources/4_obp_atts_by_obp_df.csv")
obp_atts_by_obp_df
```

```{r}
obp_atts_by_obp_df %>% arrange(desc(MINMAXRATIO))
# obp_atts_by_obp_df %>% arrange(BUYSELLYIELD)
```


```{r}
pbegin <- obp_dynatts_no_price_df %>% 
  .$DATETIMEMLLS %>% 
  min(.)
print(pbegin)

pend <- obp_dynatts_no_price_df %>% 
  .$DATETIMEMLLS %>% 
  max(.) 
print(pend)

pcolor <- function(att, plotno) {
  color = ""
  if (plotno == plotno) {
    if (att == 'BOVOL') color = "green"
    else if (att == 'SOVOL') color = "red"
    else if (att == 'BTVOL' | att == 'STVOL') color = "blue"
    else color = "white"
  } else {
    if (att == 'BOVOL') color = "green"#"aquamarine"
    else if (att == 'SOVOL') color = "red"#"coral"
    else if (att == 'BTVOL' | att == 'STVOL') color = "blue" #"cadetblue1"
    else color = "white"
  }
  # print(paste(att, plotno, color))
  return(color)
}
td_df <- obp_dynatts_no_price_df %>% 
  filter((DATETIMEMLLS >= pbegin & DATETIMEMLLS <= pend) & (ATT == "BOVOL" | ATT == "SOVOL" | ATT == "BTVOL" | ATT == "STVOL") & PRICE > 2145.0 & PRICE < 2195.0) %>%
  mutate(pcolor = map2(ATT, OBPLOTNO, ~pcolor(.x, .y)) %>% unlist())
td_df
```

```{r}
# curplotno = 302
curplotno = 1869
# curplotno = 52

pbegin <- obp_dynatts_no_price_df %>%
  filter(OBPLOTNO == curplotno) %>%
  .$DATETIMEMLLS %>%
  min(.)

pend <- obp_dynatts_no_price_df %>%
  filter(OBPLOTNO == curplotno) %>%
  .$DATETIMEMLLS %>%
  max(.)

pcolor <- function(att, plotno) {
  color = ""
  if (plotno == curplotno) {
    if (att == 'BOVOL') color = "green"
    else if (att == 'SOVOL') color = "red"
    else if (att == 'BTVOL' | att == 'STVOL') color = "#8031A7" #"blue"
    else color = "white"
  } else {
    if (att == 'BOVOL') color = "aquamarine"
    else if (att == 'SOVOL') color = "coral"
    else if (att == 'BTVOL' | att == 'STVOL') color = "#004481" #"cadetblue1"
    else color = "white"
  }
  # print(paste(att, plotno, color))
  return(color)
}

pshape <- function(att, plotno) {
  color = ""
  if (plotno == curplotno) {
    shape = 16
  } else {
    shape = 4
  }
  # print(paste(att, plotno, color))
  return(shape)
}

psize <- function(att, plotno) {
  color = ""
  if (plotno == curplotno) {
    size = 1.0
  } else {
    size = 0.5
  }
  # print(paste(att, plotno, color))
  return(size)
}

plot_df_without_rep_by_vol <- obp_dynatts_no_price_df %>% 
  filter((DATETIMEMLLS >= pbegin & DATETIMEMLLS <= pend) & (ATT == "BOVOL" | ATT == "SOVOL" | ATT == "BTVOL" | ATT == "STVOL") & PRICE > 2145.0 & PRICE < 2205.0) %>%
  mutate(pcolor = map2(ATT, OBPLOTNO, ~pcolor(.x, .y)) %>% unlist(),
         pshape = map2(ATT, OBPLOTNO, ~pshape(.x, .y)) %>% unlist(),
         psize = map2(ATT, OBPLOTNO, ~psize(.x, .y)) %>% unlist())
plot_df_without_rep_by_vol %>% filter(OBPLOTNO == curplotno)
```

```{r}
# plot_df <-  with(plot_df_without_rep_by_vol,
#                  plot_df_without_rep_by_vol[rep(1:nrow(plot_df_without_rep_by_vol),
#                                                 as.integer(log(VOLUME, base = 1.01)) + 1),])
plot_df <-  plot_df_without_rep_by_vol
```


```{r}
# dt1 <- td_df %>% filter(ATT != "BTVOL" & ATT != "STVOL")
# dt2 <- td_df %>% filter(ATT == "BTVOL" | ATT == "STVOL")
# ggplot() + 
#   geom_point(data = dt1, mapping = aes(x = TIME, y = PRICE), color = dt1$pcolor, shape = 4, size = 0.5) +
#   geom_point(data = dt2, mapping = aes(x = TIME, y = PRICE), color = dt2$pcolor, shape = 4, size = 0.5)
```

```{r}
dt11 <- plot_df %>% filter(OBPLOTNO != curplotno & ATT != "BTVOL" & ATT != "STVOL")
dt12 <- plot_df %>% filter(OBPLOTNO != curplotno & (ATT == "BTVOL" | ATT == "STVOL"))
dt21 <- plot_df %>% filter(OBPLOTNO == curplotno & ATT != "BTVOL" & ATT != "STVOL")
dt22 <- plot_df %>% filter(OBPLOTNO == curplotno & (ATT == "BTVOL" | ATT == "STVOL"))
ggplot() + 
  geom_point(data = dt11, mapping = aes(x = TIME, y = PRICE), 
             color = dt11$pcolor, shape = dt11$pshape, size = dt11$psize) + 
  geom_point(data = dt12, mapping = aes(x = TIME, y = PRICE), 
             color = dt12$pcolor, shape = dt12$pshape, size = dt12$psize) + 
  geom_point(data = dt21, mapping = aes(x = TIME, y = PRICE), 
             color = dt21$pcolor, shape = dt21$pshape, size = dt21$psize) + 
  geom_point(data = dt22, mapping = aes(x = TIME, y = PRICE), 
             color = dt22$pcolor, shape = dt22$pshape, size = dt22$psize)
```

```{r}
dt_s <- plot_df %>% filter(OBPLOTNO != curplotno & ATT == "SOVOL")
dt_b <- plot_df %>% filter(OBPLOTNO != curplotno & ATT == "BOVOL")
dt_t <- plot_df %>% filter(OBPLOTNO != curplotno & (ATT == "BTVOL" | ATT == "STVOL"))
dt_cp_sb <- plot_df %>% filter(OBPLOTNO == curplotno & ATT != "BTVOL" & ATT != "STVOL")
dt_cp_t <- plot_df %>% filter(OBPLOTNO == curplotno & (ATT == "BTVOL" | ATT == "STVOL"))

# dt_s <- plot_df %>% filter(ATT == "SOVOL")
# dt_b <- plot_df %>% filter(ATT == "BOVOL")
# dt_t <- plot_df %>% filter(ATT == "BTVOL" | ATT == "STVOL")

```

```{r}
# ggplot(dt_s, aes(x = NO, y = PRICE)) +
#   stat_density2d(mapping = aes(fill = ..level..), alpha = .5,
#                  geom = "polygon", data = dt_s) + 
#   scale_fill_viridis_c() + 
#   # theme(legend.position = 'none') +
#   scale_fill_distiller(palette = 'Reds')
```

```{r}
# ggplot(dt_b, aes(x = NO, y = PRICE)) +
#   stat_density2d(mapping = aes(fill = ..level..), alpha = .5,
#                  geom = "polygon", data = dt_b) + 
#   scale_fill_viridis_c() + 
#   # theme(legend.position = 'none') +
#   scale_fill_distiller(palette = 'Greens')
```


```{r}
ggplot(bind_rows(tibble(dt_s, gr = "s"), tibble(dt_b, gr = "b")), aes(x = NO, y = PRICE)) +
  stat_density2d(geom = "polygon", aes(fill = gr, alpha = ..level..)) + 
  scale_fill_manual(values=c("s"="#FF0000", "b"="#00FF00")) +
  geom_point(data = dt_t, mapping = aes(x = NO, y = PRICE), 
             color = dt_t$pcolor, shape = dt_t$pshape, size = dt_t$psize) +
  geom_point(data = dt_cp_sb, mapping = aes(x = NO, y = PRICE), 
             color = dt_cp_sb$pcolor, shape = dt_cp_sb$pshape, size = dt_cp_sb$psize) +
  geom_point(data = dt_cp_t, mapping = aes(x = NO, y = PRICE), 
             color = dt_cp_t$pcolor, shape = dt_cp_t$pshape, size = dt_cp_t$psize)
```

```{r}
ggplot(bind_rows(tibble(dt_b, gr = "s"), tibble(dt_s, gr = "b")), aes(x = NO, y = PRICE)) +
  stat_density2d(geom = "polygon", aes(fill = gr, alpha = ..level..)) + 
  scale_fill_manual(values=c("b"="#FF0000", "s"="#00FF00")) +
  geom_point(data = dt_t, mapping = aes(x = NO, y = PRICE), 
             color = dt_t$pcolor, shape = dt_t$pshape, size = dt_t$psize) +
  geom_point(data = dt_cp_sb, mapping = aes(x = NO, y = PRICE), 
             color = dt_cp_sb$pcolor, shape = dt_cp_sb$pshape, size = dt_cp_sb$psize) +
  geom_point(data = dt_cp_t, mapping = aes(x = NO, y = PRICE), 
             color = dt_cp_t$pcolor, shape = dt_cp_t$pshape, size = dt_cp_t$psize)
```

```{r}
ggplot(bind_rows(tibble(dt_s, gr = "s"), tibble(dt_b, gr = "b")), aes(x = NO, y = PRICE)) +
  stat_density2d(geom = "density2d", aes(color = gr)) + 
  scale_color_manual(values=c("s"="#FF0000", "b"="#00FF00")) +
  geom_point(data = dt_t, mapping = aes(x = NO, y = PRICE), 
             color = dt_t$pcolor, shape = dt_t$pshape, size = dt_t$psize) +
  geom_point(data = dt_cp_sb, mapping = aes(x = NO, y = PRICE), 
             color = dt_cp_sb$pcolor, shape = dt_cp_sb$pshape, size = dt_cp_sb$psize) +
  geom_point(data = dt_cp_t, mapping = aes(x = NO, y = PRICE), 
             color = dt_cp_t$pcolor, shape = dt_cp_t$pshape, size = dt_cp_t$psize) +
  theme_bw()
```

```{r}
td_first_30minute_df <- td_df %>% 
  filter(TIME < 1100000)
td_first_30minute_df
```

```{r}
static_plot <- ggplot() + 
  geom_point(data = td_first_30minute_df, 
             mapping = aes(x = TIME, y = PRICE), 
             color = td_first_30minute_df$pcolor, 
             shape = 4, 
             size = 0.5)
static_plot
```

```{r}
dens_plot <- ggplot(td_first_30minute_df, aes(x = NO, y = PRICE)) +
  stat_density2d(aes(fill = ..level..), alpha = .5,
                 geom = "polygon", data = td_first_30minute_df) + 
  scale_fill_viridis_c() + 
  theme(legend.position = 'none')
dens_plot
```

```{r}

```


```{r}
# animation <- static_plot +
#   transition_states(NO, transition_length = 1, state_length = 1) +
#   ease_aes('linear') +
#   shadow_mark() +
#   view_follow()
# animation
```

```{r}
# obp30mins_gif <- animate(animation, 
#                  fps = 10, 
#                  duration = 10,
#                  width = 800, height = 400, 
#                  renderer = gifski_renderer("./2gif/obp30mins.gif"))
```

