---
title: "prepare_bal_testing_dfs"
output: html_notebook
---


```{r}
library(shiny)
library(tidyverse)
```
```{r}
obps_df <- read_csv("../order-book-plot-find/resources/for_web_app/LKOH-GMKN-2007-10-08-09_obps.csv")
# obps_df <- read_csv("../order-book-plot-find/resources/for_web_app/LKOH-2007-10-08_obps.csv")
# obps_df <- read_csv("../order-book-plot-find/resources/for_web_app/s1_s2_2007_obps.csv")
obps_df <- obps_df %>% 
  mutate(TIME_S = TIME/1000)
obps_df
```


```{r}
order_atts_cumsums_df <- read_csv("../order-book-plot-find/resources/for_web_app/LKOH-GMKN-2007-10-08-09_order_atts_cumsums.csv")
# order_atts_cumsums_df <- read_csv("../order-book-plot-find/resources/for_web_app/LKOH-2007-10-08_order_atts_cumsums.csv")
# order_atts_cumsums_df <- read_csv("../order-book-plot-find/resources/for_web_app/s1_s2_2007_order_atts_cumsums.csv")
order_atts_cumsums_df
```

```{r}
obp_cum_atts_df <- read_csv("../order-book-plot-find/resources/for_web_app/LKOH-GMKN-2007-10-08-09_obp_cum_atts.csv")
# obp_cum_atts_df <- read_csv("../order-book-plot-find/resources/for_web_app/LKOH-2007-10-08_obp_cum_atts.csv")
# obp_cum_atts_df <- read_csv("../order-book-plot-find/resources/for_web_app/s1_s2_2007_obp_cum_atts.csv")
obp_cum_atts_df
```

```{r}
order_atts_cumsums_enhanced_df <- left_join(order_atts_cumsums_df, 
                                         obps_df %>% select(-OBPLOTNO, -SECCODE), 
                                         by = c("NO", "DATE")) %>% 
  select(NO, SECCODE, DATETIMEMLLS, PRICE, TRADEPRICE, VOLUME, 
         DATE, TIME_S, OBPLOTNO, ATT, VAL, 
         SHAREBAL, BPROFIT, SPROFIT, OBPMINTPRICE, OBPMAXTPRICE,
         CBOVOLtdcs, CSOVOLtdcs, BOVOLtdcs, SOVOLtdcs, BTVOLtdcs, STVOLtdcs, 
         CBOVOLobpcs, CSOVOLobpcs, BOVOLobpcs, SOVOLobpcs, BTVOLobpcs, STVOLobpcs,
         sobp, bobp, max_sobp_bobp, minus_max_sobp_bobp, stday, btday, max_std_btd,
         minus_max_std_btd)
order_atts_cumsums_enhanced_df
```

```{r}
obp_minmax_atts_df <- order_atts_cumsums_enhanced_df %>% 
  select(NO, SECCODE, DATE, OBPLOTNO, ATT,
         DATETIMEMLLS, PRICE, TRADEPRICE) %>% 
  group_by(SECCODE, DATE, OBPLOTNO) %>% 
  summarise(OBPBEGIN = min(DATETIMEMLLS), OBPEND = max(DATETIMEMLLS), 
            OBPBEGINNO = min(NO), OBPENDNO = max(NO),
            OBPMINPRICE = min(PRICE), OBPMAXPRICE = max(PRICE))
obp_minmax_atts_df
```

```{r}
obp_cum_minmax_atts_df <- left_join(obp_cum_atts_df, 
                                    obp_minmax_atts_df %>% select(SECCODE,
                                                                  DATE,
                                                                  OBPLOTNO,
                                                                  OBPBEGIN,
                                                                  OBPBEGINNO,
                                                                  OBPENDNO,
                                                                  OBPEND,
                                                                  OBPMINPRICE,
                                                                  OBPMAXPRICE),
                                    by = c("SECCODE", "DATE", "OBPLOTNO")) %>% 
  select(SECCODE, DATE, OBPLOTNO, TRADEVOL, BUYSELLOBP,
         OBPBEGIN, OBPEND, OBPBEGINNO, OBPENDNO, OBPMINPRICE, OBPMAXPRICE,
         TRADESNOTRADES) #, BUYSELLYIELD, OBPTDVOLRATIO, MINMAXRATIO)
obp_cum_minmax_atts_df
```

```{r}
oas_att_bst <- order_atts_cumsums_enhanced_df %>% 
  select(NO, SECCODE, DATE, OBPLOTNO, ATT, TRADEPRICE) %>% 
  filter(ATT == "BTVOL" | ATT == "STVOL")
oas_att_bst
```

```{r}
obp_minmax_tradeprice <- function(seccode, date, obplotno, 
                                  obpbeginno, obpendno, tradesnotrades, minmax) {
  # print(paste(length(seccode),
  #             length(date),
  #             length(obplotno),
  #             length(obpbeginno),
  #             length(obpendno),
  #             length(minmax)))
  # print(paste(seccode, date, obplotno, obpbeginno, obpendno, minmax))
  # seq(length(obplotno))
  if(tradesnotrades == "Y") {
    if (minmax == "min") {
      mint <- min(oas_att_bst %>%
                    filter(SECCODE == seccode & DATE == date & 
                             NO >= obpbeginno & NO <= obpendno) %>% 
                    .$TRADEPRICE %>%
                    cummin())
      # print(mint)
      mint
    } else if (minmax == "max") {
      maxt <- max(oas_att_bst %>%
                    filter(SECCODE == seccode & DATE == date & 
                             NO >= obpbeginno & NO <= obpendno) %>% 
                    .$TRADEPRICE %>%
                    cummax())
      # print(maxt)
      maxt
      
    } else {
      print(paste0("min or max only, not ", minmax))
      stop()
    }
  } else {
    NA
  }
}
```

```{r}
vextor_to_obp_minmax_tradeprice <- function(seccode, date, obplotno, 
                                            obpbeginno, obpendno, tradesnotrades, minmax) {
  tibble(seccode, date, obplotno, obpbeginno, obpendno, tradesnotrades,
         minmax = rep(minmax, length(obplotno))) %>% 
    pmap(obp_minmax_tradeprice) %>% 
    unlist()
}
```

```{r}
obp_cum_tprice_atts <- obp_cum_minmax_atts_df %>% 
  # sample_n(20) %>% 
  group_by(SECCODE, DATE) %>% 
  summarise(OBPLOTNO = OBPLOTNO,
            OBPMINTRADEPRICE = vextor_to_obp_minmax_tradeprice(SECCODE,
                                                               DATE,
                                                               OBPLOTNO,
                                                               OBPBEGINNO,
                                                               OBPENDNO,
                                                               TRADESNOTRADES,
                                                               "min"),
            OBPMAXTRADEPRICE = vextor_to_obp_minmax_tradeprice(SECCODE,
                                                               DATE,
                                                               OBPLOTNO,
                                                               OBPBEGINNO,
                                                               OBPENDNO,
                                                               TRADESNOTRADES,
                                                               "max"))
obp_cum_tprice_atts
```

```{r}
obp_cum_minmax_tpminmax_atts_df <- left_join(obp_cum_minmax_atts_df,
                                             obp_cum_tprice_atts,
                                             by = c("SECCODE", "DATE", "OBPLOTNO"))
obp_cum_minmax_tpminmax_atts_df
```

```{r}
obp_cum_atts_enh_df <- inner_join(obp_cum_minmax_tpminmax_atts_df,
                                  order_atts_cumsums_enhanced_df %>% select(SECCODE,
                                                                            DATE,
                                                                            OBPLOTNO,
                                                                            BPROFIT,
                                                                            SPROFIT),
                                  by = c("SECCODE", "DATE", "OBPLOTNO")) %>% 
  select(SECCODE, DATE, OBPLOTNO, TRADEVOL, BUYSELLOBP,
         BPROFIT, SPROFIT,
         OBPBEGIN, OBPEND, OBPBEGINNO, OBPENDNO, OBPMINPRICE, OBPMAXPRICE,
         OBPMINTRADEPRICE, OBPMAXTRADEPRICE, TRADESNOTRADES) %>% #, BUYSELLYIELD, OBPTDVOLRATIO, MINMAXRATIO) %>% 
  rename("seccode" = "SECCODE",
         "ddate" = "DATE",
         "obplotno" = "OBPLOTNO",
         "tradevol" = "TRADEVOL",
         "buysellobp" = "BUYSELLOBP",
         "bprofit" = "BPROFIT",
         "sprofit" = "SPROFIT",
         "obpbegin" = "OBPBEGIN",
         "obpend" = "OBPEND",
         "obpbeginno" = "OBPBEGINNO",
         "obpendno" = "OBPENDNO",
         "obpminprice" = "OBPMINPRICE",
         "obpmaxprice" = "OBPMAXPRICE",
         "obpmintradeprice" = "OBPMINTRADEPRICE",
         "obpmaxtradeprice" = "OBPMAXTRADEPRICE",
         "bprofit" = "BPROFIT",
         "sprofit" = "SPROFIT",
         "tradesnotrades" = "TRADESNOTRADES") %>% 
  distinct()
obp_cum_atts_enh_df
```

```{r}
td_vol_sum_df <- obp_cum_atts_enh_df %>% 
  group_by(seccode, ddate) %>% 
  summarise(tdvolsum = sum(tradevol))

obp_cum_atts_enh_volarranged_df <- left_join(obp_cum_atts_enh_df,
          td_vol_sum_df,
          by = c("seccode", "ddate")) %>% 
  mutate(obpshareintd = tradevol / tdvolsum) %>% 
  select(-tdvolsum) %>% 
  arrange(seccode, ddate, desc(obpshareintd))

obp_cum_atts_enh_volarranged_df
```

```{r}
options(digits.secs = 3)
obp_cum_atts_enh_volarranged_df %>%
  write_csv("../order-book-plot-find/resources/for_web_app/obp_cum_atts_enh_df.csv",
            na = "")
```

```{r}
order_atts_cumsums_enh2_df <- order_atts_cumsums_enhanced_df %>% 
  mutate(pcolor = if_else(ATT == "BOVOL", 
                          "aquamarine", 
                          if_else(ATT == "SOVOL",
                                  "coral",
                                  "#004481")),
         pshape = 4L,
         psize = 0.5)
order_atts_cumsums_enh2_df
```

```{r}
order_atts_cumsums_enh4_df <- order_atts_cumsums_enh2_df %>% 
  arrange(SECCODE, DATE, NO) %>% 
  rename("nno" = "NO",
         "seccode" = "SECCODE",
         "datetimemlls" = "DATETIMEMLLS",
         "price" = "PRICE",
         "tradeprice" = "TRADEPRICE",
         "volume" = "VOLUME",
         "ddate" = "DATE",
         "ttime_s" = "TIME_S",
         "obplotno" = "OBPLOTNO",
         "att" = "ATT",
         "val" = "VAL",
         "sharebal" = "SHAREBAL") %>% 
  select(-BPROFIT, -SPROFIT, -OBPMINTPRICE, -OBPMAXTPRICE)
# options(digits.secs = 3)
order_atts_cumsums_enh4_df %>%
  write_csv("../order-book-plot-find/resources/for_web_app/order_atts_cumsums_enh4_df.csv",
            na = "")
order_atts_cumsums_enh4_df
```

```{r}
order_atts_cumsums_enh4_df %>% 
  filter(obplotno == 48851, att == "STVOL") %>% 
  select(nno, price, att, tradeprice, sobp, bobp)
```

