library(shiny)
library(tidyverse)
library(DBI)
library(RPostgres)
library(pool)
library(dygraphs)

fluidPage(
  "order-book-plots",
  fluidRow(
    column(3,
           uiOutput("tickers")),
    column(3,
           uiOutput("dates")),
    column(6,
           uiOutput("obplots"))
  ),
  fluidRow(
    column(3,
           verbatimTextOutput("cur_ticker")),
    column(3,
           verbatimTextOutput("cur_date")),
    column(6,
           verbatimTextOutput("cur_obplot"))
  )
)